language: rust
sudo: required
dist: trusty

cache:
  cargo: true

rust:
  - stable

before_script:
  - export PATH=$PATH:~/.cargo/bin
#  - rustup component add rustfmt-preview

script:
  #  - cargo fmt --all -- --check
  - cargo test
