name: MacOS build
on: [push]

jobs:
    build:
        name: Build
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: x86_64-apple-darwin
                  override: true

            - name: Test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --target x86_64-apple-darwin
